<a href="https://colab.research.google.com/github/pratapcnanda92/Portfolioproject/blob/main/Bank_Model_Classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Bank Model - Classification

### Importing the libraries

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf
tf.__version__

'2.5.0'

## Part 1 - Data Preprocessing

### Importing the dataset

In [2]:
dataset = pd.read_csv('/content/bank-full.csv', sep=';')
X = dataset.iloc[:,:-1].values
y = dataset.iloc[:,-1].values

In [3]:
print(X)
print(y)

[[58 'management' 'married' ... -1 0 'unknown']
 [44 'technician' 'single' ... -1 0 'unknown']
 [33 'entrepreneur' 'married' ... -1 0 'unknown']
 ...
 [72 'retired' 'married' ... 184 3 'success']
 [57 'blue-collar' 'married' ... -1 0 'unknown']
 [37 'entrepreneur' 'married' ... 188 11 'other']]
['no' 'no' 'no' ... 'yes' 'no' 'no']


### Data Pre-processing

In [4]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, LabelEncoder

ct1 = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
ct2 = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [13])], remainder='passthrough')
ct3 = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [16])], remainder='passthrough')
ct4 = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [24])], remainder='passthrough')
ct5 = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [28])], remainder='passthrough')
ct6 = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [44])], remainder='passthrough')

X = np.array(ct1.fit_transform(X))
X = np.array(ct2.fit_transform(X))
X = np.array(ct3.fit_transform(X))
X = np.array(ct4.fit_transform(X))
X = np.array(ct5.fit_transform(X))
X = np.array(ct6.fit_transform(X))

#X[2,:]



In [5]:
X[2,:]

array([0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0,
       0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0,
       0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 33,
       'no', 2, 'yes', 'yes', 5, 76, 1, -1, 0], dtype=object)

In [6]:
le = LabelEncoder()
X[:,39] = le.fit_transform(X[:,39]) 
X[:,41] = le.fit_transform(X[:,41]) 
X[:,42] = le.fit_transform(X[:,42]) 
y = le.fit_transform(y)

### Splitting the dataset into the Training set and Test set

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)
print(X_train)
print(y_train)
print(X_test)
print(y_test)

[[0.0 0.0 0.0 ... 1 -1 0]
 [0.0 0.0 0.0 ... 1 -1 0]
 [0.0 0.0 0.0 ... 6 -1 0]
 ...
 [0.0 0.0 0.0 ... 2 -1 0]
 [1.0 0.0 0.0 ... 2 182 1]
 [0.0 0.0 0.0 ... 4 -1 0]]
[0 0 0 ... 1 0 0]
[[0.0 0.0 0.0 ... 15 -1 0]
 [0.0 0.0 0.0 ... 1 -1 0]
 [0.0 0.0 0.0 ... 5 -1 0]
 ...
 [0.0 0.0 0.0 ... 4 -1 0]
 [0.0 0.0 0.0 ... 2 -1 0]
 [0.0 0.0 0.0 ... 4 -1 0]]
[0 1 0 ... 0 0 1]


In [8]:
X_train[2,:]

array([0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0,
       0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0,
       1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 36, 0,
       886, 1, 1, 14, 362, 6, -1, 0], dtype=object)

## Feature Scaling

In [9]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)
print(X_train)
print(X_test)

[[-0.35072007 -0.20449071 -0.18430851 ... -0.56835853 -0.41131336
  -0.23906547]
 [-0.35072007 -0.20449071 -0.18430851 ... -0.56835853 -0.41131336
  -0.23906547]
 [-0.35072007 -0.20449071 -0.18430851 ...  1.05020406 -0.41131336
  -0.23906547]
 ...
 [-0.35072007 -0.20449071 -0.18430851 ... -0.24464601 -0.41131336
  -0.23906547]
 [ 2.85127677 -0.20449071 -0.18430851 ... -0.24464601  1.41471736
   0.1692061 ]
 [-0.35072007 -0.20449071 -0.18430851 ...  0.40277902 -0.41131336
  -0.23906547]]
[[-0.35072007 -0.20449071 -0.18430851 ...  3.96361673 -0.41131336
  -0.23906547]
 [-0.35072007 -0.20449071 -0.18430851 ... -0.56835853 -0.41131336
  -0.23906547]
 [-0.35072007 -0.20449071 -0.18430851 ...  0.72649154 -0.41131336
  -0.23906547]
 ...
 [-0.35072007 -0.20449071 -0.18430851 ...  0.40277902 -0.41131336
  -0.23906547]
 [-0.35072007 -0.20449071 -0.18430851 ... -0.24464601 -0.41131336
  -0.23906547]
 [-0.35072007 -0.20449071 -0.18430851 ...  0.40277902 -0.41131336
  -0.23906547]]


## Classification Models

#### KNN

In [10]:
from sklearn.neighbors import KNeighborsClassifier
classifier_KNN = KNeighborsClassifier(n_neighbors = 10, metric = 'minkowski', p = 2)
classifier_KNN.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=10, p=2,
                     weights='uniform')

### Logistic regression

In [11]:
from sklearn.linear_model import LogisticRegression
classifier_LG = LogisticRegression(random_state = 0)
classifier_LG.fit(X_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=0, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

### SVM

In [12]:
from sklearn.svm import SVC
classifier_SVC = SVC(kernel = 'linear', random_state = 0)
classifier_SVC.fit(X_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=False, random_state=0, shrinking=True, tol=0.001,
    verbose=False)

### Naive Bayes

In [13]:
from sklearn.naive_bayes import GaussianNB
classifier_NB = GaussianNB()
classifier_NB.fit(X_train, y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

### Decision Tree Classification

In [14]:
from sklearn.tree import DecisionTreeClassifier
classifier_DT = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifier_DT.fit(X_train, y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='entropy',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=0, splitter='best')

### Random Forest Classification

In [15]:
from sklearn.ensemble import RandomForestClassifier
classifier_RF = RandomForestClassifier(n_estimators = 20, criterion = 'entropy', random_state = 0)
classifier_RF.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='entropy', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=20,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

## Predicting the Test set results with all classifiers

In [16]:
y_pred_LG = classifier_LG.predict(X_test)
y_pred_KNN = classifier_KNN.predict(X_test)
y_pred_SVC = classifier_SVC.predict(X_test)
y_pred_NB = classifier_NB.predict(X_test)
y_pred_DT = classifier_DT.predict(X_test)
y_pred_RF = classifier_RF.predict(X_test)

## Making the Confusion Matrix

In [17]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm_LG = confusion_matrix(y_test, y_pred_LG)
cm_KNN = confusion_matrix(y_test, y_pred_KNN)
cm_SVC = confusion_matrix(y_test, y_pred_SVC)
cm_NB = confusion_matrix(y_test, y_pred_NB)
cm_DT = confusion_matrix(y_test, y_pred_DT)
cm_RF = confusion_matrix(y_test, y_pred_RF)
#print(cm_i)
#np.set_printoptions(precision=2)
LG = print("Logistic Regression Classification Accuracy Score is {:.4f} %".format(accuracy_score(y_test, y_pred_LG)*100))
print("KNN Classification Accuracy Score is {:.4f} %".format(accuracy_score(y_test, y_pred_KNN)*100))
print("SVM Classification Accuracy Score is {:.4f} %".format(accuracy_score(y_test, y_pred_SVC)*100))
print("Naive Bayes Classification Accuracy Score is {:.4f} %".format(accuracy_score(y_test, y_pred_NB)*100))
print("Decision Tree Classification Accuracy Score is {:.4f} %".format(accuracy_score(y_test, y_pred_DT)*100))
print("Random Forest Classification Accuracy Score is {:.4f} %".format(accuracy_score(y_test, y_pred_RF)*100))


Logistic Regression Classification Accuracy Score is 90.0292 %
KNN Classification Accuracy Score is 89.3214 %
SVM Classification Accuracy Score is 89.0472 %
Naive Bayes Classification Accuracy Score is 85.1544 %
Decision Tree Classification Accuracy Score is 87.3485 %
Random Forest Classification Accuracy Score is 90.0557 %
