<a href="https://colab.research.google.com/github/pratapcnanda92/Portfolioproject/blob/main/Bank_Model_Artificial_Neural_Network.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Bank Model - Classification

### Importing the libraries

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf
tf.__version__

'2.5.0'

## Part 1 - Data Preprocessing

### Importing the dataset

In [2]:
dataset = pd.read_csv('/content/bank-full.csv', sep=';')
X = dataset.iloc[:,:-1].values
y = dataset.iloc[:,-1].values

In [3]:
print(X)
print(y)

[[58 'management' 'married' ... -1 0 'unknown']
 [44 'technician' 'single' ... -1 0 'unknown']
 [33 'entrepreneur' 'married' ... -1 0 'unknown']
 ...
 [72 'retired' 'married' ... 184 3 'success']
 [57 'blue-collar' 'married' ... -1 0 'unknown']
 [37 'entrepreneur' 'married' ... 188 11 'other']]
['no' 'no' 'no' ... 'yes' 'no' 'no']


### Data Pre-processing

In [4]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, LabelEncoder

ct1 = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
ct2 = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [13])], remainder='passthrough')
ct3 = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [16])], remainder='passthrough')
ct4 = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [24])], remainder='passthrough')
ct5 = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [28])], remainder='passthrough')
ct6 = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [44])], remainder='passthrough')

X = np.array(ct1.fit_transform(X))
X = np.array(ct2.fit_transform(X))
X = np.array(ct3.fit_transform(X))
X = np.array(ct4.fit_transform(X))
X = np.array(ct5.fit_transform(X))
X = np.array(ct6.fit_transform(X))

#X[2,:]



In [5]:
X[2,:]

array([0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0,
       0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0,
       0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 33,
       'no', 2, 'yes', 'yes', 5, 76, 1, -1, 0], dtype=object)

In [6]:
le = LabelEncoder()
X[:,39] = le.fit_transform(X[:,39]) 
X[:,41] = le.fit_transform(X[:,41]) 
X[:,42] = le.fit_transform(X[:,42]) 
y = le.fit_transform(y)

### Splitting the dataset into the Training set and Test set

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)
print(X_train)
print(y_train)
print(X_test)
print(y_test)

[[0.0 0.0 0.0 ... 1 -1 0]
 [0.0 0.0 0.0 ... 1 -1 0]
 [0.0 0.0 0.0 ... 6 -1 0]
 ...
 [0.0 0.0 0.0 ... 2 -1 0]
 [1.0 0.0 0.0 ... 2 182 1]
 [0.0 0.0 0.0 ... 4 -1 0]]
[0 0 0 ... 1 0 0]
[[0.0 0.0 0.0 ... 15 -1 0]
 [0.0 0.0 0.0 ... 1 -1 0]
 [0.0 0.0 0.0 ... 5 -1 0]
 ...
 [0.0 0.0 0.0 ... 4 -1 0]
 [0.0 0.0 0.0 ... 2 -1 0]
 [0.0 0.0 0.0 ... 4 -1 0]]
[0 1 0 ... 0 0 1]


In [8]:
X_train[2,:]

array([0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0,
       0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0,
       1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 36, 0,
       886, 1, 1, 14, 362, 6, -1, 0], dtype=object)

## Feature Scaling

In [9]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)
print(X_train)
print(X_test)

[[-0.35072007 -0.20449071 -0.18430851 ... -0.56835853 -0.41131336
  -0.23906547]
 [-0.35072007 -0.20449071 -0.18430851 ... -0.56835853 -0.41131336
  -0.23906547]
 [-0.35072007 -0.20449071 -0.18430851 ...  1.05020406 -0.41131336
  -0.23906547]
 ...
 [-0.35072007 -0.20449071 -0.18430851 ... -0.24464601 -0.41131336
  -0.23906547]
 [ 2.85127677 -0.20449071 -0.18430851 ... -0.24464601  1.41471736
   0.1692061 ]
 [-0.35072007 -0.20449071 -0.18430851 ...  0.40277902 -0.41131336
  -0.23906547]]
[[-0.35072007 -0.20449071 -0.18430851 ...  3.96361673 -0.41131336
  -0.23906547]
 [-0.35072007 -0.20449071 -0.18430851 ... -0.56835853 -0.41131336
  -0.23906547]
 [-0.35072007 -0.20449071 -0.18430851 ...  0.72649154 -0.41131336
  -0.23906547]
 ...
 [-0.35072007 -0.20449071 -0.18430851 ...  0.40277902 -0.41131336
  -0.23906547]
 [-0.35072007 -0.20449071 -0.18430851 ... -0.24464601 -0.41131336
  -0.23906547]
 [-0.35072007 -0.20449071 -0.18430851 ...  0.40277902 -0.41131336
  -0.23906547]]


## ANN Model

### Initializing the ANN

In [10]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [11]:
ann.add(tf.keras.layers.Dense(units=12, activation='relu'))

### Adding the second hidden layer

In [12]:
ann.add(tf.keras.layers.Dense(units=12, activation='relu'))

### Adding the output layer

In [13]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

### Compiling and Training the model

In [14]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
1060/1060 [==============================] - 3s 2ms/step - loss: 0.2734 - accuracy: 0.8898
Epoch 2/100
1060/1060 [==============================] - 2s 1ms/step - loss: 0.2163 - accuracy: 0.9037
Epoch 3/100
1060/1060 [==============================] - 2s 1ms/step - loss: 0.2098 - accuracy: 0.9059
Epoch 4/100
1060/1060 [==============================] - 2s 1ms/step - loss: 0.2062 - accuracy: 0.9065
Epoch 5/100
1060/1060 [==============================] - 2s 1ms/step - loss: 0.2038 - accuracy: 0.9076
Epoch 6/100
1060/1060 [==============================] - 2s 1ms/step - loss: 0.2019 - accuracy: 0.9086
Epoch 7/100
1060/1060 [==============================] - 2s 1ms/step - loss: 0.2004 - accuracy: 0.9090
Epoch 8/100
1060/1060 [==============================] - 2s 1ms/step - loss: 0.1991 - accuracy: 0.9096
Epoch 9/100
1060/1060 [==============================] - 2s 1ms/step - loss: 0.1979 - accuracy: 0.9101
Epoch 10/100
1060/1060 [==============================] - 2s 1ms/step - l

## Predicting the Test set results

In [15]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [1 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [1 1]]


## Making the Confusion Matrix

In [16]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[9449  529]
 [ 591  734]]


0.9009112624966823